#index:
#    path: /
#    controller: App\Controller\DefaultController::index

tasks:
    path: /tareas
    controller: App\Controller\TaskController::index

task_detail:
    path: /tarea/{id}
    controller: App\Controller\TaskController::taskDetail

task_create:
    path: /crear-tarea
    controller: App\Controller\TaskController::createTask

my_tasks:
    path: /mis-tareas
    controller: App\Controller\TaskController::myTasks

task_edit:
    path: /editar-tarea/{id}
    controller: App\Controller\TaskController::editTask

register:
    path: /registro
    controller: App\Controller\RegistrationController::register

login:
    path: /login
    controller: App\Controller\LoginController::login

logout:
    path: /logout
    controller: App\Controller\LoginController::logout